#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -pe omp 16
#$ -o /projectnb/bf528/users/dreadlocks/project_4/curator/run_log/run_salmon_count3_o
#$ -e /projectnb/bf528/users/dreadlocks/project_4/curator/run_log/run_salmon_count3_e

module load salmon/1.1.0

FILEPATH=/projectnb/bf528/users/dreadlocks/project_4/curator
FASTQPATH=/projectnb/bf528/users/dreadlocks/project_4/curator/data/fastq

salmon alevin -l ISR -1 $FASTQPATH/SRR3879607/SRR3879607_1_bc.fastq.gz \
$FASTQPATH/SRR3879608/SRR3879608_1_bc.fastq.gz \
$FASTQPATH/SRR3879609/SRR3879609_1_bc.fastq.gz \
$FASTQPATH/SRR3879610/SRR3879610_1_bc.fastq.gz \
-2 $FASTQPATH/SRR3879607/SRR3879607_2.fastq.gz \
$FASTQPATH/SRR3879608/SRR3879608_2.fastq.gz \
$FASTQPATH/SRR3879609/SRR3879609_2.fastq.gz \
$FASTQPATH/SRR3879610/SRR3879610_2.fastq.gz \
-i $FILEPATH/salmon_index/ -p 16 -o $FILEPATH/result/salmon_count/GSM2230759 \
--tgMap $FILEPATH/data/ref/tgMap.tsv \
--whitelist $FILEPATH/result/barcode_count/GSM2230759_wl.csv \
--end 5 --barcodeLength 19 --umiLength 6

