#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -pe omp 16
#$ -o /projectnb/bf528/users/dreadlocks/project_4/curator/run_log/run_salmon_count4_o
#$ -e /projectnb/bf528/users/dreadlocks/project_4/curator/run_log/run_salmon_count4_e

module load salmon/1.1.0

FILEPATH=/projectnb/bf528/users/dreadlocks/project_4/curator
FASTQPATH=/projectnb/bf528/users/dreadlocks/project_4/curator/data/fastq

salmon alevin -l ISR -1 $FASTQPATH/SRR3879611/SRR3879611_1_bc.fastq.gz \
$FASTQPATH/SRR3879612/SRR3879612_1_bc.fastq.gz \
$FASTQPATH/SRR3879613/SRR3879613_1_bc.fastq.gz \
-2 $FASTQPATH/SRR3879611/SRR3879611_2.fastq.gz \
$FASTQPATH/SRR3879612/SRR3879612_2.fastq.gz \
$FASTQPATH/SRR3879613/SRR3879613_2.fastq.gz \
-i $FILEPATH/salmon_index/ -p 16 -o $FILEPATH/result/salmon_count/GSM2230760 \
--tgMap $FILEPATH/data/ref/tgMap.tsv \
--whitelist $FILEPATH/result/barcode_count/GSM2230760_wl.csv \
--end 5 --barcodeLength 19 --umiLength 6

